config/routes.rb
Gigster::Application.routes.draw do

  root :to => 'tops#index'

  get "infomations/about"

  resources :gigs, :only => [:new, :create, :show, :edit, :update, :index, :favorite] do
    collection do
      get :thanks
      post :favorite
      post :comment
    end
  end

  resources :houses, :only => [:new, :create, :show, :edit, :update, :index] do
    collection do
      get :thanks
    end
  end

  resources :artists, :only => [:new, :create, :show, :edit, :update, :index, :favorite_artist] do
    collection do
      get :thanks
      post :favorite_artist
      post :comment_artist
    end
  end

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :city, :country, :created_at, :day, :detail, :gunre, :image, :members_ids, :name, :updated_at, :yotube_url, :soundcloud_url, :view_count

  mount_uploader :image, FlyerUploader
  paginates_per 100

  has_many :favorite_artists
  has_many :users, :through => :favorite_artists

  has_many :comment_artists
  has_many :users, :through => :comment_artists

  validates :name, :presence => true, :allow_blank => true, :length => {:maximum => 50}
  validates :gunre, :presence => true, :allow_blank => true, :length => {:maximum => 50}
  #validates :image, :presence => true, :allow_blank => true
  validates :detail, :presence => true, :allow_blank => true, :length => {:maximum => 10000}
  validates :country, :presence => true, :allow_blank => true

end

app/controllers/artists_controller.rb
# -*- coding: utf-8 -*-

class ArtistsController < ApplicationController

  # GET /gigs/new
  # GET /gigs/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # POST /gigs
  # POST /gigs.json
  def create

    @artist = Artist.new(params[:artist])

    @artist.users_ids = current_user.id
    @artist.yotube_url = @artist.yotube_url.gsub('watch?v=','embed/')

    if @artist.save
      redirect_to thanks_artists_url
    else
      render :new
    end
  end

  def thanks
  end

  def favorite_artist
    fav = FavoriteArtist.where(:user_id => current_user.id, :artist_id => params[:id] ).first
    unless fav
      @fav = FavoriteArtist.new()
      @fav.user_id = current_user.id
      @fav.artist_id = params[:id]
      @fav.save
    end

    @artist = Artist.find(params[:id])
    render action: "show",id: params[:id]
  end

  def comment_artist
    @comment = CommentArtist.new()
    @comment.user_id = current_user.id
    @comment.artist_id = params[:id]
    @comment.content = params[:content]
    @comment.save

    @artist = Artist.find(params[:id])
    render action: "show",id: params[:id]
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @artist = Artist.find(params[:id])
    @artist.view_count = @artist.view_count + 1
    @artist.save

    @meta_og_title = @artist.name
    @meta_og_url = "http://gigster.jp/artist/" + @artist.id.to_s
    @meta_og_image = @artist.image_url
    @meta_og_description = "Gigster/ギグ共有サービス"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /gigs/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # PUT /gigs/1
  # PUT /gigs/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end

  # GET /gigs
  # GET /gigs.json
  def index

    @search = Artist.search()
    @artists = Artist.order("name").page params[:page]

    if params[:q]
      @search = Artist.search(params[:q])
      @artists = @search.result.order("name")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

end

app/views/artists/_form.html.erb
   <div class="container">

    <%= form_for(@artist) do |f| %>
      <!-- Forms
      ================================================== -->
      <div class="bs-docs-section">
        <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h2 id="forms">アーティストを登録する</h2>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6">
            <div class="well">
              <form class="bs-example form-horizontal">
                <fieldset>
                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">アーティスト名<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.text_field :name,:class => "form-control",:id => "inputEmail",:placeholder => "name" %>
                      <%= error_tag(@artist, :name) %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">画像<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.file_field :image,:class => "form-control" %>
                      <%= error_tag(@artist, :image) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">ジャンル<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.text_field :gunre,:class => "form-control",:id => "inputEmail",:placeholder => "gunre" %>
                      <%= error_tag(@artist, :gunre) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textArea" class="col-lg-2 control-label">詳細<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.text_area :detail,:class => "form-control",:placeholder => "detail" %>
                      <%= error_tag(@artist, :detail) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="select" class="col-lg-2 control-label">国<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.text_field :country,:class => "form-control",:placeholder => "country" %>
                      <%= error_tag(@artist, :country) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">
                    SoundCloud URL（任意）</label>
                    <div class="col-lg-10">
                      <%= f.text_field :soundcloud_url,:class => "form-control",:id => "inputEmail",:placeholder => "soundcloud_url" %>
                      <%= error_tag(@artist, :soundcloud_url) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">
                    YouTube URL（任意）</label>
                    <div class="col-lg-10">
                      <%= f.text_field :yotube_url,:class => "form-control",:id => "inputEmail",:placeholder => "youtube" %><br />
                      <%= error_tag(@artist, :yotube_url) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button class="btn btn-default" >Cancel</button>
                      <%= f.submit :class => "btn btn-primary" %>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>

        </div>
      </div>
      <% end %>
    </div>

app/views/artists/edit.html.erb
<%= render 'form' %>

app/views/artists/index.html.erb
      <div class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
            </ul>

            <%= search_form_for @search, :url => '/artists', :class => 'navbar-form navbar-left' do |f| %>

              <%= f.text_field :name_cont, :class => 'form-top-control col-lg-8', :placeholder => 'アーティスト名' %>
              <%= f.country_select :country_cont,[ "Japan","United States","United Kingdom","Australia", "France","Germany","Spain","Ireland","Italy","Sweden", "Brazil","Canada", "Denmark", "Israel","Singapore", "India", "Indonesia", "Korea, Republic of" , "China","Hong Kong", "Thailand","South Africa"], {:prompt => "国"}, {:class => 'form-top-control'} %>

              <%= f.submit '検索する', :class => "btn btn-success" %>
            <% end %>

          </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
      </div><!-- /.navbar -->

      <% if user_signed_in? %>
      <div class="container">
          <a href="./artists/new" >
              <button type="button" class="btn btn-success" >アーティストを登録する</button>
          </a>
      </div>

      <% end %>

      <h3 id="tables" align="center" ><%= "--- アーティスト一覧 ---" %></h3>

      <div class="content">

          <article class="hentry-home">
          <div class="container">
            <% tmp_day = false %>
            <% @artists.each do |artist| %>

                <% if tmp_day != artist.day %>
                    <% if tmp_day != false %>
                          </tbody>
                        </table>
                      </div><!-- /example -->
                    <% end %>

                    <% tmp_day = artist.day %>
                    <div class="bs-example">
                      <table class="table table-striped table-bordered table-hover">
                      <tbody>
                <% end %>
                <tr data-href="/artists/<%= artist.id %>" >
                  <td width="200" ><%= image_tag artist.image_url, :size => "150x150" %></td>
                  <td><h4><%= artist.name %><br/>
                      (<%= artist.country %>)　( <%= artist.gunre %> )　
                      <%= artist.view_count %> Views</h4>
                      <%= simple_format(cut_off(artist.detail, 100)) %></td>
                  <td width="100">
                    <% if user_signed_in? %>
                        <%= button_to "お気に入り♥", { :controller=>"artists", :action => "favorite_artist", :id => artist.id }, :confirm => "お気に入りにいれますか?", :method => :favorite, :class=>"btn btn-danger", :style=>"margin: 50px 0 0 0;" %>
                    <% else %>
                        <%= button_to "お気に入り♥", user_omniauth_authorize_path(:facebook), :class=>"btn btn-danger", :style=>"margin: 50px 0 0 0;" %>
                    <% end %><br/>
                  </td>
                </tr>
            <% end %>

              </tbody>
            </table>
          </div><!-- /example -->

          <%= link_to 'TOPへ戻る', '/' %><br/><br/>

          </div>
          </article>

      </div>
      <% if params[:q].nil? %>
        <div style="color: #ffffff"><%= paginate @artists %></div>
      <% end  %>

app/views/artists/new.html.erb
<%= render 'form' %>

app/views/artists/show.html.erb
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1&appId=153617311511977";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    <div id="fb-root"></div>

    <div class="container">

      <!-- Typography
      ================================================== -->
      <div class="bs-docs-section">
        <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h2 id="type"><%= @artist.name %></h2>
            </div>
          </div>
        </div>

        <h3>
        <%= @artist.day %>(<%= @artist.country %>)　
        <script type="text/javascript" language="javascript">
        document.write('<div class="fb-like" data-href="http://gigster.jp/artist/<%= @artist.id %>" data-width="450" data-layout="button_count" data-show-faces="true" data-send="true"></div>');
        </script>　
        <%= @artist.view_count %> Views</h3><br/>
        </h3>

        <div class="bs-example">
          <p class="lead"><%= @artist.gunre %></p>
        </div>

        <% if user_signed_in? && current_user.id == @artist.users_ids %>
          <%= link_to '(編集する)', edit_artist_path(@artist), :style => "color:18bc9c;" %><br>
        <% end %>

        <%= image_tag @artist.image_url, :size => "350x300" %>

        <!-- Headings -->

        <div class="row">
          <div class="col-lg-4">

            <div class="bs-example">
              <p class="lead"><%= br(@artist.detail) %></p>
            </div>
            <br/>

            <% if @artist.soundcloud_url != "" %>
              <iframe width="450" height="100" scrolling="no" frameborder="no" src="<%= @artist.soundcloud_url %>"></iframe>
              <br/><br/>
            <% end %>

            <% if @artist.yotube_url != "" %>
              <iframe width="450" height="300" src="<%= @artist.yotube_url %>?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
              <br/><br/>
            <% end %>

          </div>
        </div>

        <table>
        <tr>
          <td>

            <% if user_signed_in? %>
                <%= button_to "お気に入り♥", { :controller=>"artists", :action => "favorite_artist", :id => @artist.id }, :confirm => "お気に入りにいれますか?", :method => :favorite, :class=>"btn btn-danger", :style=>"margin: 70px 0 0 0;" %>
            <% else %>
                <%= button_to "お気に入り♥", user_omniauth_authorize_path(:facebook), :class=>"btn btn-danger", :style=>"margin: 70px 0 0 0;" %>
            <% end %>

          </td>
          <td>
            <a href="http://ticket-search.pia.jp/pia/search_all.do?kw=<%=@artist.name%>" class="btn btn-info" style="background-color:#00acee;border-color:#00acee;margin: 70px 0px 0 20px;" target="_blank" type="submit" value="チケットぴあ" >チケットぴあ
          </td>
        </tr>
        </table><br/>


        <div class="bs-example">
          <p class="lead" style="color:#e74c3c;">お気に入りユーザ</p>
          <% if user_signed_in? %>
              <% @artist.favorite_artists.each do |f| %>
                　<%= f.user.name %><br/>
              <% end %>
          <% else %>
            <p><font color="red">※お気に入りユーザを見るにはログインか会員登録して下さい。</font></p>
          <% end %>

        </div><br/>

        <div class="bs-example">
          <p class="lead" style="color:#18bc9c;" >コメント</p>
          <% if user_signed_in? %>
              <% @artist.comment_artists.each do |c| %>
                  <div class="bsa well">
                  　<%= c.created_at.strftime("%m/%d %H:%M")  %>　
                  　<%= c.content %>　
                  　by <%= c.user.name %>
                  </div>
              <% end %>

              <%= form_tag('/artists/comment_artist/') do %>
                <form class="bs-example form-horizontal">
                  <div class="form-group">
                    　<%= text_area_tag 'content', "", :class => "form-control" %>
                  </div>

                  <div class="form-group">
                    <%= submit_tag ["コメントする"], :class => "btn btn-primary" %>
                  </div>
                  <input name="id" type="hidden" value="<%= @artist.id %>">
                </form>
              <% end %>

          <% else %>
            <p><font color="red">※コメントを見るにはログインか会員登録して下さい。</font></p><br/>
            Facebook会員登録<%= button_to "→　Sign in with Facebook　←", user_omniauth_authorize_path(:facebook), :class=>"btn btn-info" %><br/>
            Twitter会員登録
             <%= button_to "→　Sign in with Twitter　←", user_omniauth_authorize_path(:twitter), :class=>"btn btn-info", :style=>"background-color:#00acee;border-color:#00acee;" %><br/>

          <% end %>
        </div>

        <%= link_to '一覧へ戻る', '/artists' %><br/><br/>
        <%= link_to 'TOPへ戻る', '/' %>
        <br/><br/>

    </div>

app/views/artists/thanks.erb
<h1></h1>

    <div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-6">
            <h2>アーティスト登録完了</h2>
          </div>
          <div class="col-lg-6">
            <div class="bsa well">
                <div id="bsap_1277971" class="bsarocks bsap_c466df00a3cd5ee8568b5c4983b6bb19">
                  Thank you!!!!!!!!
                </div>
            </div>
          </div>
        </div>
      </div>
      <%= link_to '一覧へ戻る', '/artists' %>
    </div>