config/routes.rb
Gigster::Application.routes.draw do

  root :to => 'tops#index'

  get "infomations/about"

  resources :gigs, :only => [:new, :create, :show, :edit, :update, :index, :favorite] do
    collection do
      get :thanks
      post :favorite
      post :comment
    end
  end

  resources :houses, :only => [:new, :create, :show, :edit, :update, :index] do
    collection do
      get :thanks
    end
  end

  resources :artists, :only => [:new, :create, :show, :edit, :update, :index, :favorite_artist] do
    collection do
      get :thanks
      post :favorite_artist
      post :comment_artist
    end
  end

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

end

app/models/gig.rb
class Gig < ActiveRecord::Base

  attr_accessible :created_at, :day, :flyer, :flyer_cache, :infomation, :members_ids, :name, :country, :updated_at, :yotube_url, :city, :soundcloud_url, :view_count, :city, :gunre, :prefecture_code

  include JpPrefecture
  jp_prefecture :prefecture_code

  has_many :favorites
  has_many :users, :through => :favorites

  has_many :comments
  has_many :users, :through => :comments

  mount_uploader :flyer, FlyerUploader
  paginates_per 100

  validates :name, :presence => true, :allow_blank => true, :length => {:maximum => 50}
  validates :infomation, :presence => true, :allow_blank => true, :length => {:maximum => 10000}
  validates :day, :presence => true, :allow_blank => true
  #validates :flyer, :presence => true, :allow_blank => true
  validates :prefecture_code, :presence => true, :allow_blank => true

end

app/controllers/gigs_controller.rb
# -*- coding: utf-8 -*-

class GigsController < ApplicationController

  # GET /gigs/new
  # GET /gigs/new.json
  def new
    @gig = Gig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gig }
    end
  end

  # POST /gigs
  # POST /gigs.json
  def create

    @gig = Gig.new(params[:gig])

    @gig.users_ids = current_user.id
    @gig.yotube_url = @gig.yotube_url.gsub('watch?v=','embed/')

    if @gig.save
      redirect_to thanks_gigs_url
    else
      render :new
    end

  end

  def thanks
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @gig = Gig.find(params[:id])
    @gig.view_count = @gig.view_count + 1
    @gig.save

    @comment = Comment.new()

    @meta_og_title = @gig.name
    @meta_og_url = "http://gigster.jp/gigs/" + @gig.id.to_s
    @meta_og_image = @gig.flyer_url
    @meta_og_description = "Gigster/ギグ共有サービス"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gig }
    end
  end

  def favorite
    fav = Favorite.where(:user_id => current_user.id, :gig_id => params[:id] ).first
    unless fav
      @fav = Favorite.new()
      @fav.user_id = current_user.id
      @fav.gig_id = params[:id]
      @fav.save
    end

    @gig = Gig.find(params[:id])
    render action: "show",id: params[:id]
  end

  def comment
    @comment = Comment.new()
    @comment.user_id = current_user.id
    @comment.gig_id = params[:id]
    @comment.content = params[:content]
    @comment.save

    @gig = Gig.find(params[:id])
    render action: "show",id: params[:id]
  end

  # GET /gigs/1/edit
  def edit
    @gig = Gig.find(params[:id])
  end

  # PUT /gigs/1
  # PUT /gigs/1.json
  def update
    @gig = Gig.find(params[:id])

    @gig.yotube_url = @gig.yotube_url.gsub('watch?v=','embed/')

    respond_to do |format|
      if @gig.update_attributes(params[:gig])
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig = Gig.find(params[:id])
    @gig.destroy

    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end

  # GET /gigs
  # GET /gigs.json
  def index

    @search = Gig.search()
    @gigs = Gig.where("day > ?", Time.now - 1.days).order("day").page params[:page]

    if params[:q]
      @search = Gig.search(params[:q])
      @gigs = @search.result.order("day")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gigs }
    end
  end

end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_form.html.erb
   <div class="container">

    <%= form_for(@gig, :html => { :multipart => true }) do |f| %>
      <!-- Forms
      ================================================== -->
      <div class="bs-docs-section">
        <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h2 id="forms">イベントを登録する</h2>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6">
            <div class="well">
              <form class="bs-example form-horizontal">
                <fieldset>
                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">イベント名<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.text_field :name,:class => "form-control",:id => "inputEmail",:placeholder => "name" %>
                      <%= error_tag(@gig, :name) %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">フライヤー画像<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.file_field :flyer,:class => "form-control" %>
                      <%= f.hidden_field :flyer_cache %>
                      <%= error_tag(@gig, :flyer) %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="textArea" class="col-lg-2 control-label">詳細<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.text_area :infomation,:class => "form-control",:placeholder => "infomation" %>
                      <%= error_tag(@gig, :infomation) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="select" class="col-lg-2 control-label">日付<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.date_select :day,:class => "form-control",:id => "select" %><br />
                      <%= error_tag(@gig, :day) %>
                    </div>
                  </div>

                  <label for="select" class="col-lg-2 control-label">都道府県<font color="#18bc9c">（必須）</font></label>
                    <div class="col-lg-10">
                      <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, :prompt => true,:class => "form-control",:id => "inputEmail",:placeholder => "name" %>
                      <%= error_tag(@gig, :prefecture_code) %>
                  </div><br/>

                  <label for="select" class="col-lg-2 control-label">町（任意）</label>
                    <div class="col-lg-10">
                     <%= f.text_field :city,:class => "form-control",:id => "inputEmail",:placeholder => "city" %>
                      <%= error_tag(@gig, :city) %>
                  </div><br/>

                  <label for="select" class="col-lg-2 control-label">ジャンル（任意）</label>
                    <div class="col-lg-10">
                     <%= f.text_field :gunre,:class => "form-control",:id => "inputEmail",:placeholder => "gunre" %>
                      <%= error_tag(@gig, :gunre) %>
                  </div><br/>

                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">
                    SoundCloud URL（任意）</label>
                    <div class="col-lg-10">
                      <%= f.text_field :soundcloud_url,:class => "form-control",:id => "inputEmail",:placeholder => "soundcloud_url" %>
                      <%= error_tag(@gig, :soundcloud_url) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">
                    YouTube URL（任意）</label>
                    <div class="col-lg-10">
                      <%= f.text_field :yotube_url,:class => "form-control",:id => "inputEmail",:placeholder => "youtube" %><br />
                      <%= error_tag(@gig, :yotube_url) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button class="btn btn-default">Cancel</button>
                      <%= f.submit :class => "btn btn-primary" %>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>

        </div>
      </div>
      <% end %>
    </div>

app/views/gigs/index.html.erb
      <div class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
            </ul>

            <%= search_form_for @search, :url => '/gigs', :class => 'navbar-form navbar-left' do |f| %>

              <%= f.text_field :name_cont, :class => 'form-top-control col-lg-8', :placeholder => '音楽イベント名' %>
              <%= f.collection_select :prefecture_code_in, JpPrefecture::Prefecture.all, :code, :name, {:prompt => "都道府県"}, {:class => 'form-top-control'} %>

              <%= f.date_select :day_gteq, {:default => Date.today}, {:class => 'form-top-control'} %>

              <%= f.submit '検索する', :class => "btn btn-success" %>
            <% end %>

          </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
      </div><!-- /.navbar -->

      <% if user_signed_in? %>
        <div class="container" >
            <a href="./gigs/new" >
                <button type="button" class="btn btn-success" >イベントを登録する</button>
            </a>
        </div>
      <% end %>

      <h3 id="tables" align="center" ><%= "------ イベント一覧------" %></h3>

      <div class="content">

          <article class="hentry-home">
          <div class="container">
            <% tmp_day = false %>
            <% @gigs.each do |gig| %>

                <% if tmp_day != gig.day %>
                    <% if tmp_day != false %>
                          </tbody>
                        </table>
                      </div><!-- /example -->
                    <% end %>

                    <% tmp_day = gig.day %>
                    <div class="page-header">
                      <h3 id="tables"><%= gig.day.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[gig.day.wday]})") %></h3>
                    </div>
                    <div class="bs-example">
                      <table class="table table-striped table-bordered table-hover">
                      <tbody>
                <% end %>
                <tr data-href="/gigs/<%= gig.id %>" >
                    <td width="200" ><%= image_tag gig.flyer_url, :size => "150x150" %></td>
                    <td><h4><%= gig.name %><br/>
                      (<% pref = JpPrefecture::Prefecture.find gig.prefecture_code %> <%= pref.name %>, <%= gig.city %>  )　(<%= gig.gunre %> )
                      <%= gig.view_count %> Views</h4>
                      <%= simple_format(cut_off(gig.infomation, 100)) %></td>
                    <td width="100">
                      <% if user_signed_in? %>
                          <%= button_to "お気に入り♥", { :controller=>"gigs", :action => "favorite", :id => gig.id }, :confirm => "お気に入りにいれますか?", :method => :favorite, :class=>"btn btn-danger", :style=>"margin: 50px 0 0 0;" %>
                      <% else %>
                          <%= button_to "お気に入り♥", user_omniauth_authorize_path(:facebook), :class=>"btn btn-danger", :style=>"margin: 50px 0 0 0;" %>
                      <% end %><br/>
                    </td>
                </tr>
            <% end %>

              </tbody>
            </table>
          </div><!-- /example -->

          <%= link_to 'TOPへ戻る', '/' %><br/><br/>

          </div>
          </article>

          <% if params[:q].nil? %>
            <div style="color: #ffffff"><%= paginate @gigs %></div>
          <% end  %>


      </div>

app/views/gigs/show.html.erb
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1&appId=153617311511977";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    <div id="fb-root"></div>

    <div class="container">

      <!-- Typography
      ================================================== -->
      <div class="bs-docs-section">
        <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h2 id="type"><%= @gig.name %></h2>
            </div>
          </div>
        </div>
        <h3>
        <%= @gig.day %>　(<% pref = JpPrefecture::Prefecture.find @gig.prefecture_code %> <%= pref.name %> , <%= @gig.city %>)　
        <script type="text/javascript" language="javascript">
        document.write('<div class="fb-like" data-href="http://gigster.jp/gigs/<%= @gig.id %>" data-width="450" data-layout="button_count" data-show-faces="true" data-send="true"></div>');
        </script>　
        <%= @gig.view_count %> Views</h3><br/>

        <% if user_signed_in? && current_user.id == @gig.users_ids %>
          <%= link_to '(編集する)', edit_gig_path(@gig), :style => "color:18bc9c;" %>
          <br/>
        <% end %>

        <%= image_tag @gig.flyer_url, :size => "300x250" %>

        <!-- Headings -->

        <div class="row">
          <div class="col-lg-4">

            <div class="bs-example">
              <p class="lead"><%= br(@gig.infomation) %></p>
            </div>
            <br/>

            <% if @gig.soundcloud_url != "" %>
              <iframe width="450" height="100" scrolling="no" frameborder="no" src="<%= @gig.soundcloud_url %>"></iframe>
              <br/>
            <% end %>

            <% if @gig.yotube_url != "" %>
              <iframe width="450" height="300" src="<%= @gig.yotube_url %>?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
              <br/>
            <% end %>

            <!--
            <div class="fb-comments" data-href="<%=@meta_og_url%>" data-width="400"></div>
            -->
          </div>
        </div>

        <table>
        <tr>
          <td>
            <% if user_signed_in? %>
                <%= button_to "お気に入り♥", { :controller=>"gigs", :action => "favorite", :id => @gig.id }, :confirm => "お気に入りにいれますか?", :method => :favorite, :class=>"btn btn-danger", :style=>"margin: 70px 0 0 0;" %>
            <% else %>
                <%= button_to "お気に入り♥", user_omniauth_authorize_path(:facebook), :class=>"btn btn-danger", :style=>"margin: 70px 0 0 0;" %>
            <% end %>
          </td>
          <td>
            <a href="http://ticket-search.pia.jp/pia/search_all.do?kw=<%=@gig.name%>" class="btn btn-info" style="background-color:#00acee;border-color:#00acee;margin: 70px 0px 0 20px;" target="_blank" type="submit" value="チケットぴあ" >チケットぴあ
          </td>
        </tr>
        </table>
        <br/><br/>

        <div class="bs-example">
          <p class="lead" style="color:#e74c3c;">お気に入りユーザ</p>
          <% if user_signed_in? %>
              <% @gig.favorites.each do |f| %>
                　<%= f.user.name %><br/>
              <% end %>
          <% else %>
            <p><font color="red">※お気に入りユーザを見るにはログインか会員登録して下さい。</font></p>
          <% end %>

        </div><br/>

        <div class="bs-example">
          <p class="lead" style="color:#18bc9c;" >コメント</p>
          <% if user_signed_in? %>
              <% @gig.comments.each do |c| %>
                  <div class="bsa well">
                  　<%= c.created_at.strftime("%m/%d %H:%M")  %>　
                  　<%= c.content %>　
                  　by <%= c.user.name %>
                  </div>
              <% end %>

              <%= form_tag('/gigs/comment/') do %>
                <form class="bs-example form-horizontal">
                  <div class="form-group">
                    　<%= text_area_tag 'content', "", :class => "form-control" %>
                  </div>

                  <div class="form-group">
                    <%= submit_tag ["コメントする"], :class => "btn btn-primary" %>
                  </div>
                  <input name="id" type="hidden" value="<%= @gig.id %>">
                </form>
              <% end %>

          <% else %>
            <p><font color="red">※コメントを見るにはログインか会員登録して下さい。</font></p><br/>
            Facebook会員登録<%= button_to "→　Sign in with Facebook　←", user_omniauth_authorize_path(:facebook), :class=>"btn btn-info" %><br/>
            Twitter会員登録
             <%= button_to "→　Sign in with Twitter　←", user_omniauth_authorize_path(:twitter), :class=>"btn btn-info", :style=>"background-color:#00acee;border-color:#00acee;" %><br/>

          <% end %>
        </div>

        <%= link_to '一覧へ戻る', '/gigs' %><br/><br/>
        <%= link_to 'TOPへ戻る', '/gigs' %>
        <br/><br/>

    </div>

app/views/gigs/thanks.erb
<h1></h1>

    <div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-6">
            <h2>イベント登録完了</h2>
          </div>
          <div class="col-lg-6">
            <div class="bsa well">
                <div id="bsap_1277971" class="bsarocks bsap_c466df00a3cd5ee8568b5c4983b6bb19">
                  Thank you!!!!!!!!
                </div>
            </div>
          </div>
        </div>
      </div>
      <%= link_to '一覧へ戻る', '/gigs/' %>
    </div>